voice_config:
- id: default
  phonemizer: OpenUtau.Core.DefaultPhonemizer
- id: tiger
  singer: TIGER_DS_v110
  renderer: DIFFSINGER
  phonemizer: OpenUtau.Core.DiffSinger.DiffSingerARPAPlusEnglishPhonemizer
- id: nero
  singer: Lunai Pack v151/04 Nero/configs
  renderer: DIFFSINGER
  phonemizer: OpenUtau.Core.DiffSinger.DiffSingerARPAPlusEnglishPhonemizer
- id: peyton
  singer: peiton_ds_1.5_beta
  renderer: DIFFSINGER
  phonemizer: OpenUtau.Core.DiffSinger.DiffSingerARPAPlusEnglishPhonemizer
- id: tiger-fr
  singer: TIGER_DS_v110
  renderer: DIFFSINGER
  phonemizer: OpenUtau.Core.DiffSinger.DiffSingerFrenchPhonemizer
- id: nero-fr
  singer: Nero_v151/configs
  renderer: DIFFSINGER
  phonemizer: OpenUtau.Core.DiffSinger.DiffSingerFrenchPhonemizer
track_config:
- id: default
  tracks:
  - voice_id: default
- id: ttbb-barbershop
  tracks:
  - voice_id: tiger
    track_name: Tenor
    pan: -60.0
  - voice_id: tiger
    track_name: Lead
    pan: -25.0
    volume: 3.0
  - voice_id: tiger
    track_name: Bari
    pan: -60.0
  - voice_id: peyton
    track_name: Bass
    pan: 10.0
    volume: 1.0
- id: ttbb-barbershop-fr
  tracks:
  - voice_id: tiger-fr
    track_name: Tenor
    pan: -60.0
  - voice_id: tiger-fr
    track_name: Lead
    pan: -25.0
    volume: 3.0
  - voice_id: tiger-fr
    track_name: Bari
    pan: -60.0
  - voice_id: nero-fr
    track_name: Bass
    pan: 10.0
    volume: 6.0
- id: 5-part
  tracks:
  - voice_id: tiger
    track_name: Part 1
    pan: -60.0
  - voice_id: tiger
    track_name: Part 2
    pan: -25.0
  - voice_id: tiger
    track_name: Part 3
    pan: -60.0
  - voice_id: peyton
    track_name: Part 4
  - voice_id: peyton
    track_name: Part 5
    pan: 10.0
    volume: 6.0
default_lyric: doo
