[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "xml2ustx"
version = "0.1.0"
description = "Tool to convert XML vocal parts to ustx files for OpenUTAU."
authors = ["Krysta Petrie"]
license = "GPL"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
jsonpickle = ">=4.0.1,<5.0.0"
streamlit = ">=1.41.1,<2.0.0"
pyyaml = ">=6.0.2,<7.0.0"
music21 = ">=9.3.0,<10.0.0"
PyQt5 = ">=5.15.0,<6.0.0"
