#!/bin/zsh

function mp3() {
  for process in "$@" ; do;
    ffmpeg -i "${process}" -acodec libmp3lame -ab 320k "${process:r}.mp3"
  done;
};

function left() {
  if [ "$#" -ne 5 ]; then
        echo "Usage: mix.sh left left.wav right1.wav right2.wav right3.wav outfile";
        exit 1
  fi;
  echo "mix left $1 $2 $3 $4 $5"
  ffmpeg -i "$1" -i "$2" -i "$3" -i "$4" -filter_complex "[0:a][1:a][2:a][3:a]amerge=inputs=4,pan=stereo|FL<c0|FR<0.33*c1+0.33*c2+0.33*c3[a]" -ac 2 -map "[a]" -c:v copy $5.mp3;
};

function stereo() {
  if [ "$#" -ne 5 ]; then
        echo "Usage: mix.sh stereo tenor.wav lead.wav bari.wav bass.wav outfile";
        exit 1
  fi;
  echo "mix stereo $1 $2 $3 $4 $5"
  ffmpeg -i "$1" -i "$2" -i "$3" -i "$4" -filter_complex "[0:a][1:a][2:a][3:a]amerge=inputs=4,pan=stereo|FL<0.65*c0+0.7*c1+0.35*c2+0.45*c3|FR<0.35*c0+0.6*c1+0.65*c2+0.6*c3[a]" -ac 2 -map "[a]" -c:v copy $5.mp3;
};

function all() {
  if [ "$#" -ne 5 ]; then
        echo "Usage: mix.sh all tenor.wav lead.wav bari.wav bass.wav outname";
        exit 1
  fi;

  left "$1" "$2" "$3" "$4" "$5 - Tenor";
  left "$2" "$1" "$3" "$4" "$5 - Lead";
  left "$3" "$1" "$2" "$4" "$5 - Bari";
  left "$4" "$1" "$2" "$3" "$5 - Bass";
  stereo "$1" "$2" "$3" "$4" "$5 - Full Mix";
};

function here() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: mix.sh here outname"
    exit 1
  fi;

  TENOR="$(find . -name '*Tenor.wav')"
  LEAD="$(find . -name '*Lead.wav')"
  BARI="$(find . -name '*Bari.wav')"
  BASS="$(find . -name '*Bass.wav')"

  echo "Found: $TENOR $LEAD $BARI $BASS"
  all "$TENOR" "$LEAD" "$BARI" "$BASS" "$1"
};

"$@"